blog/urls.py
"""Настройка маршрутизации URL для Django-приложения blog."""

from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('home/', views.cookies_and_comm, name='home'),
    path('home/<post_id>', views.post_info, name='home_post_id')
] 

project/urls.py
"""Настройка маршрутизации URL для Django-приложения blog."""

from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    # При переходе на '/blog/' происходит маршрутизация на файл urls.py из Django-приложения blog.
    path('blog/', include('blog.urls')),

    # При переходе на '/accounts/' происходит маршрутизация на файл urls.py из приложения registration.
    path('accounts/', include('registration.urls')),

    # При переходе на '/admin/' происходит перенаправление на стандартный интерфейс администратора Django.
    path('admin/', admin.site.urls)
    
]

registration/urls.py
"""Настройка маршрутизации URL для Django-приложения registration."""

from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registration/', views.register, name='registration')
]

blog/models.py
"""Определение моделей в Django-приложении blog."""

from django.db import models 
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin


class Post(models.Model):

    """
    Класс Post - модель для создания постов блога. Наследуется от базового класса models.Model.
    Атрибуты класса: 
        title - название поста, тип поля CharField. 
        description - описание поста, тип поля CharField.
        image - изображение поста, тип поля ImageField.

    """

    title = models.CharField(max_length = 50, verbose_name = "Post's Title")   
    description = models.CharField(max_length = 1000, verbose_name = "Post's Description")   
    image = models.ImageField(upload_to="static/img/post", blank=True, null=True, verbose_name="Post's Image")   

    def __str__(self):  # метод, который возвращает строковое представление экземпляра класса.
        return f"{self.title}"
    
class Comment(models.Model):

    """
    Класс Comment - модель для создания комментариев к постам блога. Наследуется от базового класса models.Model.
    Атрибуты класса: 
        user - пользователь, который оставил комментарий.
        post - пост, к которому был оставлен комментарий.
        info_comm - текст комментария, тип поля TextField.
        nickname - псевдоним пользователя, тип поля CharField.

    """

    user = models.ForeignKey(User, null = True, blank = True, on_delete = models.SET_DEFAULT, default="")
    post = models.ForeignKey(Post, null = True, blank = True, on_delete = models.SET_DEFAULT, default="")
    info_comm = models.TextField(max_length = 200, verbose_name = "Comment's info", null = True)
    nickname = models.CharField(max_length = 30, verbose_name = "Nickname", null = True)
    
    def __str__(self): # метод, который возвращает строковое представление экземпляра класса.
        return f"{self.info_comm}"

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment

def cookies_and_comm(request):    

    """
    Функция обрабатывает GET и POST запросы для страницы 'home/'.
    Если метод запроса - GET, функция создает словарь с информацией о всех постах из модели Post и комментариями к ним.
    Если метод запроса - POST, функция сохраняет новый комментарий в базу данных Comment.

    """

    if request.method == 'POST':

        # Получаем информацию о комментарии
        comment = request.POST['comment']
        post_id = request.POST['post_id']
        user=request.user

        # Сохраняем новый комментарий в базу данных
        post = Post.objects.get(id=post_id)
        Comment(user=user, post=post, info_comm=comment, nickname=user).save()

    # Получаем информацию о всех постах и комментариях к ним из базы данных
    get_posts_name = Post.objects.all()
    info_db_dict = {}
    comm_inf = {}

    # Создаем словари с информацией о постах и о комментариях
    for i in get_posts_name:
        info_db_dict[i]= list(Post.objects.filter(title= str(i)).values('title', 'description', 'image','id'))
        post_id = list(Post.objects.filter(title= str(i)).values('id'))[0]['id']

        # получаем список комментариев к текущему посту
        comment_info = list(Comment.objects.filter(post_id = post_id).values('info_comm', 'nickname'))
        comm_inf[f"comment_info_{i}"] = list(
            Comment.objects.filter(post_id = post_id).values('info_comm', 'nickname')
            )

    # Возвращаем страницу home/ и передаем информацию о пользователях, постах и комментариях.    
    return render(
        request, 'home.html', {'users_name': request.user,'big_data': info_db_dict}
        )


def post_info(request,post_id):    

    """
    Функция обрабатывает GET и POST запросы для страницы 'home/'.
    Если метод запроса - GET, функция создает словарь с информацией о всех постах из модели Post и комментариями к ним.
    Если метод запроса - POST, функция сохраняет новый комментарий в базу данных Comment.

    """
   
    if request.method == 'POST':

        # Получаем информацию о комментарии
        comment = request.POST['comment']
  
        user=request.user

        # Сохраняем новый комментарий в базу данных
        post = Post.objects.get(id=post_id)
        Comment(user=user, post=post, info_comm=comment, nickname=user).save()

    # Создаем словари с информацией о постах
    info_db_dict = list(Post.objects.filter(id = post_id).values('title', 'description', 'image'))

    # получаем список комментариев к текущему посту
    comm_info = list(
        Comment.objects.filter(post_id = post_id).values('info_comm', 'nickname')
        )
  
    return render(
        request, 'post_info.html', {'users_name': request.user,'big_data':info_db_dict,'comm_info':comm_info}
        )

blog/templates/base_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" integrity="undefined" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/burger_menu.css' %}" integrity="undefined" crossorigin="anonymous">    
    <title>Document</title>
</head>
<body id="head1">
  {% block header %}
    <nav  class="navbar navbar-expand-md navbar-light sticky-top">
      <a href="{% url 'blog:home' %}"><img class="logo" src="{% static 'img/logo.png' %}" width="40" height="32" alt=""></a>
      <div class="container-fluid text-center" style="display: flex; flex-direction: row-reverse;">
        <a class="navbar-brand" href="#"></a>
          <div class="d-flex flex-row-reverse">
            <div type="button" class=" burg-btn-close " id = 'burg-btn-close' style="display: none;">
              <a id="burg-btn-close" >x</a>
            </div>
            <button class="navbar-toggler d-block" id = 'burger-btn' type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
            <div class="nav-item px-2">
              <a class="nav-link px-2 link-secondary" href="#head1">Вверх</a>
            </div>
          </div>
      </div>
    </nav>
    <div class="burger-menu" id="burger-menu" style="display: none;">
        <div class="conteiner-burg">
          {% if request.user.is_authenticated %}
          <h7>{{ users_name }}</h7>
          <a href="{% url 'registration:logout' %}">Log out</a>
          {% else %}
          <a href="{% url 'registration:registration' %}">Sign up</a>
          <a href="{% url 'registration:login' %}">Log in</a>
          {% endif %}
        </div>
    </div>
    <script src="{% static 'js/app.js' %}">
    </script>
  {% endblock header %}

  {% block content %}
  {% endblock content %}
</body>
</html>

blog/templates/home.html
{% extends 'base_blog.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        integrity="undefined" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" integrity="undefined" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/burger_menu.css' %}" integrity="undefined" crossorigin="anonymous">
    <title>My Webpage</title>

</head>

<body>

    {% block content %}
    <div class="wrapper">
        <div class="container">
            {% for i in big_data %}
            <div class="post-container">
                <div>
                    <div class="post-img">
                        <img src="/../{{ i.image }}" alt="">
                    </div>
                    <a href="{% url 'blog:home_post_id' post_id=i.id %}" class="post-title">
                        <h1>
                        {{ i.title }}
                    </h1>
                    </a>
                    <div class="post-description">
                        {{ i.description }}
                    </div>
                    <div class="post-user-submition">
                       
                        <div class="post-grade"></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endblock %}

</body>

</html>

blog/templates/post_info.html
{% extends 'base_blog.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" integrity="undefined" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/burger_menu.css' %}" integrity="undefined" crossorigin="anonymous">  
    <title>My Webpage</title>

</head>

<body>

    {% block content %}

            {% for i in big_data %}
            <div class="wrapp-comm">
                <div class="post-container-object">
                    
                    <div class="post-img-comm">
                        <img src="/../{{ i.image }}" alt="">
                    </div>
                    <h4 class="post-title-comm">
                        {{ i.title }}
                    </h4>
                    <div class="post-description">
                        {{ i.description }}
                    </div>
                </div>
                    <div class="post-user-submition">
                        
                        <div class="all-comm"  id="all-comm">
                            {% for i in comm_info %}
                            <div class="comm-text">
                                <div class="nickname">{{i.nickname}}:</div>
                             
                                {{i.info_comm}}
                            </div>
                            
                        {% endfor %}
                        </div>
                        {% if request.user.is_authenticated %}
                        <form method='post' class="post-comment">
                            {% csrf_token %}                                               
                            <input type="hidden" name="post_id" value="{{i.id}}">
                            <input name='comment' type="text">
                            <button class="btn btn-lg btn-secondary btn-block" type="submit">Отправить комментарий</button>

                        </form>
                        {% else %}
                        <div class="post-comment">                       

                        
                            <input type="hidden" name="post_id" value="{{i.id}}">
                            <input name='comment' type="text">
                            <a href="{% url 'registration:login' %}" ><button class="btn btn-lg btn-secondary btn-block" type="submit">Отправить комментарий</button></a>

                        </div>
                        {% endif %}
                        <div class="post-grade"></div>
                    </div>
                </div>
            </div>
            {% endfor %}
    

    {% endblock %}

</body>

</html>